.TH KDUMPID 1 "4 Nov 2011"
.SH NAME
KdumpID \- A tool to identify kernel memory dumps
.SH SYNOPSIS
.B kdumpid
.I [-v] <dumpfile>
.SH "DESCRIPTION"
.B kdumpid
provides a fast and reliable method to find out the most
important information about an unknown kernel crash dump,
such as the architecture and kernel release.  Think of it
as a kind of "file" utility for kernel dumps.
.LP
At present,
.B kdumpid
can read:
.LP
\- LKCD files
.br
\- DISKDUMP/KDUMP files
.br
\- ELF dumps (including support for both Xen Dom0 and DomU).
.LP
The following architectures are fully supported:
.LP
\- x86
.br
\- x86-64
.br
\- ppc
.br
\- ppc64
.br
\- s390
.br
\- s390x.
.LP
Other architectures may produce some output if the information
can be found in the file header.
.SH "OPERATION"
By default,
.B kdumpid
will print the kernel dump's format, architecture and version.
.SH "OPTIONS"
.TP
\fB\-v\fR
Try to extract and print additional information from
the memory dump, such as: the machine type, the full
kernel banner string and the kernel configuration flavor.
.SH "SEE ALSO"
.BR crash (8),
.BR makedumpfile (8),
.BR kdump (7).
.SH AUTHOR
KdumpID was written by Petr Tesarik.
